name: Pipeline CI

on:
  push:
    branches:

  pull-request:


jobs:
  sast:
    name: SAST()




  build:
    name: build




  lint-and-quality:
    name: lint&quality




  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v7

      - name: Setup node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test